// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdUjwbqVJWYvb-codN5xGuXRfs8lW_-3U',
    appId: '1:217457041529:web:80b48956c078133872b4a8',
    messagingSenderId: '217457041529',
    projectId: 'pawtrust1234',
    authDomain: 'pawtrust1234.firebaseapp.com',
    storageBucket: 'pawtrust1234.firebasestorage.app',
    measurementId: 'G-1Y010GLTNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBoKwfebXL0CTk-U9FZHyk3XKBbm5cwk',
    appId: '1:217457041529:android:ed1110614182616172b4a8',
    messagingSenderId: '217457041529',
    projectId: 'pawtrust1234',
    storageBucket: 'pawtrust1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xTgkumdSYOXxGcoMsq_e8JCSAihgYkM',
    appId: '1:217457041529:ios:981a6658bf65b7d772b4a8',
    messagingSenderId: '217457041529',
    projectId: 'pawtrust1234',
    storageBucket: 'pawtrust1234.firebasestorage.app',
    iosBundleId: 'com.example.pawtrust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xTgkumdSYOXxGcoMsq_e8JCSAihgYkM',
    appId: '1:217457041529:ios:981a6658bf65b7d772b4a8',
    messagingSenderId: '217457041529',
    projectId: 'pawtrust1234',
    storageBucket: 'pawtrust1234.firebasestorage.app',
    iosBundleId: 'com.example.pawtrust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdUjwbqVJWYvb-codN5xGuXRfs8lW_-3U',
    appId: '1:217457041529:web:94c9ffd7dd51f68a72b4a8',
    messagingSenderId: '217457041529',
    projectId: 'pawtrust1234',
    authDomain: 'pawtrust1234.firebaseapp.com',
    storageBucket: 'pawtrust1234.firebasestorage.app',
    measurementId: 'G-T93Q876S1F',
  );
}
